# Generated by Django 4.2.1 on 2023-06-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/blog')),
                ('text', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='JobLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationType', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'JobLocationType',
                'verbose_name_plural': 'JobLocationTypes',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'JobType',
                'verbose_name_plural': 'JobTypes',
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='static/product_images')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seeker',
                'verbose_name_plural': 'Seekers',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='static/product_images')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter',
                'verbose_name_plural': 'Recruiters',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTile', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.country')),
                ('locationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.joblocationtype')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recruiter')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.jobtype')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recruiter'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='static/cv')),
                ('coverLetter', models.FileField(upload_to='static/coverLetter')),
                ('similarity', models.FloatField(blank=True, default=None, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.seeker')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
