# Generated by Django 4.2.1 on 2023-06-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_company_logo_job_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
    ]
